/*
tn.h - token type
programmer - 장민지
date - 2022.04.24
*/

enum tokentypes {TEOF, TLBRACE, TRBRACE, TLBRACKET, TRBRACKET, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, 
TSTAR, TSLASH, TMOD, TEQUAL, TNOTEQU, TLESS, TGREAT, TNOT, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, 
TDIVASSIGN, TMODASSIGN, TIDENT, TNUMBER, TMINUS, TASSIGN, TSEMI, TLPAREN, TRPAREN, TCOMMA, TCARR, 
TFLOAT, TERROR, TNEWLINE};